### PR TITLE
one minor typo fix, permissions fix, and updated gitignore

### PR DESCRIPTION
**Pull request by movingelectrons**

### CODE REVIEW

**Comment by movingelectrons** [comment]
my bad, should I just trash this fork and re-fork yours?  mostly just to keep git clean

**Comment by etaletai13** [comment]
This shooould work just right.
`yarn add github:etaletai13/desktop` in an empty dir should end up going through the whole build process -- so, certainly, a `yarn` command tossed at the cloned desktop repo should! If it doesn't, the ux module is likely the issue. I'm going to go fix a gmc bug now.

**Comment by movingelectrons** [comment]
no dice

jeromes@jtop ~/Projects/musicoin/desktop_new $ yarn add github:etaletai13/desktop 
yarn add v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[3/3] ⡀ musicoin-wallet
[-/3] ⡀ waiting...
[-/3] ⡀ waiting...
[-/3] ⡀ waiting...
error /home/jeromes/Projects/musicoin/desktop_new/node_modules/musicoin-wallet: Command failed.
Exit code: 1
Command: mkdir -p bin/gmc && cp node_modules/\@musicoin/gmc/bin/gmc bin/gmc/ && mv node_modules/\@musicoin/ux ./interface && yarn secondstage && exit 0
Arguments: 




jeromes@jtop ~/Projects/musicoin/desktop_new $

**Comment by etaletai13** [comment]
@movingelectrons I wasn't actually suggesting that's how you should do it, I'm sorry. You should definitely be cloning and working with that; I was saying that it should be able to go through the process. In the case I see there, it has to be seeing two bits in reverse, or you already have node_modules present somehow. It didn't install any deps.

**Pull request closed without merging**
